- name: Deploy PetClinic App
  hosts: my-deploy-server
  become: yes
  tasks:
    - name: Copy app to the deployment server
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /app/spring-petclinic.jar
      with_fileglob:
        - target/*.jar

    - name: Run spring-petclinic app
      shell: java -jar /app/spring-petclinic.jar > /dev/null 2>&1 &
      async: 5
      poll: 0