- name: Deploy PetClinic App
  hosts: my-deploy-server
  become: yes
  become_method: docker
  tasks:
    - name: Copy app to the deployment server
      ansible.builtin.copy:
        src: target/spring-petclinic-*.jar
        dest: /app/spring-petclinic.war

    - name: Run app
      ansible.builtin.shell: "java -jar target/*.jar"
      args:
        chdir: /app